### ISSUE TITLE
this._init is not a function

### ISSUE THREAD

**Issue by delvedor** [mcollina/boot-in-the-arse#7]
Hi, I get this error while trying to use `boot-in-the-arse`.
What am I doing wrong?

[Here](https://gist.github.com/delvedor/321d463c7b7a47581b3839d4931bac3b) the code.

Error:
```bash
.../node_modules/boot-in-the-arse/boot.js:119
  this._init()
       ^

TypeError: this._init is not a function
    at Function.Boot.use (.../node_modules/boot-in-the-arse/boot.js:119:8)
    at Object.<anonymous> (.../example.js:27:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by mcollina** [comment]
Try removing `fastify.use = boot.use` completely :)

**Comment by delvedor** [comment]
Here's how is the function:
```javascript
function build () {
  const router = wayfarer('/404')
  const map = new Map()
  bootInTheArse(fastify)
  router.on('/404', defaultRoute)

  // shorthand methods
  fastify.get = get
  fastify.post = post
  fastify.put = put
  // extended route
  fastify.route = route

  return fastify

  function fastify (req, res) {
    router(stripUrl(req.url), req, res)
  }
```

And here's the error:
```bash
.../example.js:27
fastify.use(require('./plugin'), {}, console.log)
        ^

TypeError: fastify.use is not a function
    at Object.<anonymous> (.../example.js:27:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by delvedor** [comment]
Problem solved, for the records, it was missing a `'{}'`:
```javascript
bootInTheArse(fastify, {})
```
